# Generated by Django 4.2.7 on 2025-07-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaOfInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("center_lat", models.FloatField()),
                ("center_lng", models.FloatField()),
                ("bbox_north", models.FloatField()),
                ("bbox_south", models.FloatField()),
                ("bbox_east", models.FloatField()),
                ("bbox_west", models.FloatField()),
                (
                    "satellite_source",
                    models.CharField(
                        choices=[
                            ("sentinel-2", "Sentinel-2"),
                            ("landsat-8", "Landsat-8"),
                            ("landsat-9", "Landsat-9"),
                            ("bhoonidhi", "Bhoonidhi"),
                        ],
                        default="sentinel-2",
                        max_length=20,
                    ),
                ),
                ("cloud_cover_threshold", models.FloatField(default=20.0)),
                ("change_threshold", models.FloatField(default=0.3)),
                ("is_active", models.BooleanField(default=True)),
                ("area_km2", models.FloatField(default=0.0)),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aois",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Area of Interest",
                "verbose_name_plural": "Areas of Interest",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("notification_preferences", models.JSONField(default=dict)),
                ("api_key", models.CharField(blank=True, max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="SatelliteImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("satellite", models.CharField(max_length=50)),
                ("scene_id", models.CharField(max_length=100, unique=True)),
                ("acquisition_date", models.DateTimeField()),
                ("cloud_cover", models.FloatField()),
                ("file_path", models.CharField(max_length=500)),
                ("file_size_mb", models.FloatField(default=0.0)),
                ("is_processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "aoi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.areaofinterest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Satellite Image",
                "verbose_name_plural": "Satellite Images",
                "ordering": ["-acquisition_date"],
            },
        ),
    ]
